# This is a basic workflow to help you get started with Actions

name: tweet-on-release

# Controls when the workflow will run
on:
  release:
    types: [published]

jobs:
  send-release-tweet:
    runs-on: ubuntu-latest

    env:
      CONSUMER_API_KEY: ${{ secrets.TWITTER_CONSUMER_API_KEY }}
      CONSUMER_API_SECRET_KEY: ${{ secrets.TWITTER_CONSUMER_API_SECRET_KEY }}
      ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
      ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
  
    steps:
      - name: Tweet summary
        id: summary
        uses: snow-actions/tweet@v1.2.0
        with:
          status: |
            🥳Release test-repo ${{ github.event.release.name }}
          
            Changelog:
          
            ${{ github.event.release.html_url }}
          
            drop a ⭐if you liked the project :)
            #DEVCommunity #OpenSource #100DaysOfCode  #javascript
